puts "The students of Villans Academy"
puts "_____________"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Jocker"
puts "Joffrey Baratheon"
puts "Norman Bates"
